# Generated by Django 6.0.8 on 2026-09-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='cb_onboarding_one_default_flow')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('profile', 'Profile'), ('questionnaire', 'Questionnaire'), ('ai_chat', 'AI chat'), ('plan', 'Plan'), ('custom', 'Custom')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('required', models.BooleanField(default=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cb_onboarding.onboardingflow')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='cb_onboarding.onboardingflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_progress_records', to='cb_onboarding.onboardingstep')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='FlowAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cb_onboarding.onboardingflow')),
            ],
            options={
                'ordering': ('-priority', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('group__isnull', False), ('min_level__isnull', False), _connector='OR'), name='cb_onboarding_assignment_has_rule')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='cb_onboarding_unique_step_order'),
        ),
        migrations.AddConstraint(
            model_name='onboardingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'flow'), name='cb_onboarding_unique_user_flow_progress'),
        ),
    ]
