"""Provisional package-first schema; do not tag before C3.7 compatibility proof."""

# Generated by Django 6.0.8 on 2026-09-05 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('purpose', models.CharField(choices=[('onboarding', 'Onboarding'), ('feedback', 'Feedback'), ('general', 'General')], default='general', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('long_text', 'Long text'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('scale', 'Scale / rating'), ('number', 'Number')], max_length=20)),
                ('prompt', models.TextField()),
                ('help_text', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('archetype', models.CharField(help_text='Short label shown next to the name everywhere in Studio, e.g. "The Engineer transitioning to AI". Required.', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_questionnaire', models.ForeignKey(blank=True, help_text='Optional default onboarding questionnaire for this persona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=300)),
                ('allows_free_text', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.questionnaire')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('persona_signal', models.CharField(blank=True, default='', max_length=20)),
                ('turn_version', models.PositiveBigIntegerField(db_default=0, default=0)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation', to='questionnaires.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('long_text', 'Long text'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('scale', 'Scale / rating'), ('number', 'Number')], max_length=20)),
                ('prompt', models.TextField()),
                ('help_text', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_questions', to='questionnaires.response')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_questions', to='questionnaires.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('number_value', models.IntegerField(blank=True, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.responsequestion')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=300)),
                ('allows_free_text', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('response_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.responsequestion')),
                ('source_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.questionoption')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerOptionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_texts', to='questionnaires.answer')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_texts', to='questionnaires.responsequestionoption')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='answers', to='questionnaires.responsequestionoption'),
        ),
        migrations.CreateModel(
            name='OnboardingTurnAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField()),
                ('member_message_hash', models.CharField(max_length=64)),
                ('admitted_version', models.PositiveBigIntegerField()),
                ('transport', models.CharField(choices=[('stream', 'Stream'), ('non_stream', 'Non-stream')], max_length=16)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('outcome', models.CharField(blank=True, default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('provider_call_count', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('disconnected', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('first_delta_at', models.DateTimeField(blank=True, null=True)),
                ('last_delta_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField()),
                ('admission_to_provider_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ttft_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('persistence_tail_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('persistence_to_done_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('total_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_status', models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='not_needed', max_length=16)),
                ('notification_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('notification_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('notification_last_error', models.CharField(blank=True, default='', max_length=120)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_attempts', to='questionnaires.onboardingconversation')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'lease_expires_at'], name='questionnai_status_1aef50_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'request_id'), name='unique_onboarding_turn_request'), models.UniqueConstraint(condition=models.Q(('status', 'processing')), fields=('conversation',), name='one_processing_onboarding_turn')],
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status', 'reviewed_at', '-submitted_at'], name='response_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'respondent'), name='unique_response_per_respondent_per_questionnaire'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'submitted'), models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), _connector='OR'), name='response_draft_review_fields_null'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), ('reviewed_at__isnull', False), _connector='OR'), name='response_reviewer_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='answeroptiontext',
            constraint=models.UniqueConstraint(fields=('answer', 'selected_option'), name='unique_text_per_answer_option'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_question_per_response'),
        ),
    ]
