# Generated by Django 6.0.8 on 2026-09-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('role_label', models.CharField(blank=True, max_length=160)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('booking_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('current_load', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call profile',
                'verbose_name_plural': 'Call profiles',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CommunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invite', 'Invite'), ('remove', 'Remove'), ('reactivate', 'Reactivate'), ('link', 'Link'), ('check', 'Check')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Audit Log',
                'verbose_name_plural': 'Community Audit Logs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='SlackAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_version', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('eligibility', 'Eligibility'), ('onboarding', 'Onboarding'), ('operator', 'Operator'), ('import', 'Import')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_access_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
            },
        ),
        migrations.CreateModel(
            name='UnmatchedBookedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_booked_call_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('invitee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('invitee_name', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=20)),
                ('calendly_event_uri', models.CharField(max_length=500, unique=True)),
                ('calendly_invitee_uri', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('scheduling_url', models.URLField(blank=True, default='', max_length=500)),
                ('reschedule_url', models.URLField(blank=True, default='', max_length=500)),
                ('cancel_url', models.URLField(blank=True, default='', max_length=500)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_booked_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-scheduled_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BookedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_name', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=20)),
                ('calendly_event_uri', models.CharField(max_length=500, unique=True)),
                ('calendly_invitee_uri', models.CharField(blank=True, default='', max_length=500)),
                ('reschedule_url', models.URLField(blank=True, default='', max_length=500)),
                ('cancel_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_calls', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_calls', to='community.callhost')),
            ],
            options={
                'ordering': ('-scheduled_at', '-created_at'),
                'indexes': [models.Index(fields=['member', 'status'], name='community_member_status_idx'), models.Index(fields=['host', 'status'], name='community_host_status_idx')],
            },
        ),
    ]
