"""Provisional package-first schema; C3.7 will add the verified donor replaces inventory."""

# Generated by Django 6.0.8 on 2026-09-05 14:41

import community_base.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_resend_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_resend_claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('email_preferences', models.JSONField(blank=True, default=dict)),
                ('soft_bounce_count', models.PositiveSmallIntegerField(default=0)),
                ('bounce_state', models.CharField(choices=[('none', 'No bounce'), ('soft', 'Soft bounce'), ('permanent', 'Permanent bounce')], db_index=True, default='none', max_length=16)),
                ('bounce_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('last_bounce_diagnostic', models.TextField(blank=True, default='')),
                ('slack_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('slack_member', models.BooleanField(db_index=True, default=False)),
                ('slack_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('theme_preference', models.CharField(blank=True, default='', max_length=10)),
                ('preferred_timezone', models.CharField(blank=True, default='', max_length=100)),
                ('dashboard_dismissals', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('signup_source', models.CharField(choices=[('unknown', 'Unknown (pre-existing row)'), ('newsletter', 'Newsletter subscribe'), ('download', 'Download request'), ('signup', 'Email + password signup'), ('oauth', 'OAuth signup'), ('imported', 'Bulk import'), ('staff_create', 'Staff-created')], db_index=True, default='unknown', max_length=32)),
                ('account_activated', models.BooleanField(db_index=True, default=False)),
                ('import_source', models.CharField(choices=[('manual', 'Manual / self signup'), ('slack', 'Slack workspace'), ('course_db', 'Course database'), ('stripe', 'Stripe customers')], db_index=True, default='manual', max_length=32)),
                ('imported_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('import_metadata', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
                'ordering': ('-date_joined',),
                'abstract': False,
            },
            managers=[
                ('objects', community_base.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(choices=[('merge', 'Added by an account merge'), ('manual', 'Operator-added'), ('stripe_relay', 'Billing relay address'), ('account_change', 'Former login email after account change')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Alias',
                'verbose_name_plural': 'Email Aliases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('slack', 'Slack workspace'), ('course_db', 'Course database'), ('stripe', 'Stripe customers')], db_index=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dry_run', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('users_created', models.PositiveIntegerField(default=0)),
                ('users_updated', models.PositiveIntegerField(default=0)),
                ('users_skipped', models.PositiveIntegerField(default=0)),
                ('emails_queued', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=2, validators=[community_base.accounts.models.validate_country_code])),
                ('work_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('student', 'Student'), ('between_roles', 'Between roles'), ('not_working', 'Not working'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('organisation', models.CharField(blank=True, default='', max_length=160)),
                ('professional_role', models.CharField(blank=True, choices=[('data_engineer', 'Data engineer'), ('data_scientist', 'Data scientist'), ('data_analyst', 'Data analyst'), ('ml_engineer', 'Machine-learning engineer'), ('software_engineer_backend', 'Backend software engineer'), ('software_engineer_other', 'Other software engineer'), ('student_stem', 'STEM student'), ('student_non_stem', 'Non-STEM student'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=32)),
                ('seniority', models.CharField(blank=True, choices=[('learning', 'Learning'), ('entry', 'Entry'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead_or_manager', 'Lead or manager'), ('executive_or_founder', 'Executive or founder'), ('not_applicable', 'Not applicable'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('about', models.TextField(blank=True, default='', max_length=1000)),
                ('ambitions', models.TextField(blank=True, default='', max_length=1000)),
                ('why_joined', models.TextField(blank=True, default='', max_length=1000)),
                ('github_url', models.URLField(blank=True, max_length=500, validators=[community_base.accounts.models.validate_profile_url])),
                ('linkedin_url', models.URLField(blank=True, max_length=500, validators=[community_base.accounts.models.validate_profile_url])),
                ('website_url', models.URLField(blank=True, max_length=500, validators=[community_base.accounts.models.validate_profile_url])),
                ('completion_version', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('confirmed_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', 'Export'), ('delete', 'Delete'), ('deletion_request', 'Deletion request')], max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('pending_delivery', 'Pending delivery'), ('requested', 'Requested'), ('delivery_failed', 'Delivery failed')], max_length=16)),
                ('old_user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('normalized_email_hash', models.CharField(db_index=True, max_length=64)),
                ('email_domain', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('row_count_summary', models.JSONField(blank=True, default=dict)),
                ('blocker_reason', models.CharField(blank=True, default='', max_length=64)),
                ('request_ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['request_type', 'status', '-requested_at'], name='accounts_privacy_state_idx'), models.Index(fields=['blocker_reason'], name='accounts_privacy_block_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_type', 'deletion_request'), ('status__in', ('pending_delivery', 'requested')), ('old_user_id__isnull', False)), fields=('old_user_id',), name='unique_active_deletion_request')],
            },
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.EmailField(max_length=254)),
                ('new_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('confirmed_at__isnull', True), ('invalidated_at__isnull', True)), fields=('user',), name='unique_active_email_change_request_per_user')],
            },
        ),
    ]
