"""Provisional: adds `account_id` to the `django_session` table django.contrib.sessions
already owns. `AccountSession` is unmanaged (`managed = False`), so the `CreateModel`
operation above only records model state; it issues no DDL. The `RunPython` step below
does the actual `ALTER TABLE`, mirroring the donor migration
(AISL `accounts/migrations/0027_accountsession_account_id.py`) column for column. Kept
provisional, like `0001_provisional_initial`, until the AISL donor inventory and
equivalence checks pass (C3.7); AISL already carries this exact column in production, so
it owns that check. DTC has no such column and simply gains one."""

# Generated by Django 6.0.8 on 2026-09-17 12:10

from django.db import migrations, models


def add_account_id_column(apps, schema_editor):
    AccountSession = apps.get_model('accounts', 'AccountSession')
    field = AccountSession._meta.get_field('account_id')
    schema_editor.add_field(AccountSession, field)


def remove_account_id_column(apps, schema_editor):
    AccountSession = apps.get_model('accounts', 'AccountSession')
    field = AccountSession._meta.get_field('account_id')
    schema_editor.remove_field(AccountSession, field)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_provisional_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('account_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'django_session',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.RunPython(add_account_id_column, remove_account_id_column),
    ]
