# Generated by Django 6.0.8 on 2026-09-05 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_public_id_sequence(apps, _schema_editor):
    apps.get_model("events", "EventPublicIdSequence").objects.get_or_create(
        pk=1, defaults={"next_public_id": 1}
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('none', 'No fixed cadence')], default='weekly', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=100)),
                ('required_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('host', 'Host'), ('instructor', 'Instructor'), ('speaker', 'Speaker')], default='host', max_length=20)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('bio_html', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EventPublicIdSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_public_id', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='events_public_id_sequence_singleton'), models.CheckConstraint(condition=models.Q(('next_public_id__gt', 0)), name='events_public_id_sequence_positive')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('public_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('q_and_a', 'Q&A')], default='standard', max_length=20)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('custom', 'Custom URL'), ('in_person', 'In person')], default='zoom', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=100)),
                ('zoom_meeting_id', models.CharField(blank=True, default='', max_length=255)),
                ('zoom_join_url', models.URLField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('required_level', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, default='', max_length=500)),
                ('recording_s3_url', models.URLField(blank=True, default='', max_length=500)),
                ('recording_embed_url', models.URLField(blank=True, default='', max_length=500)),
                ('transcript_url', models.URLField(blank=True, default='', max_length=500)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('timestamps', models.JSONField(blank=True, default=list)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ics_sequence', models.PositiveIntegerField(default=0)),
                ('calendar_uid', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('source_repo', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('source_path', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('source_commit', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('series_position', models.PositiveIntegerField(blank=True, null=True)),
                ('title_is_auto', models.BooleanField(default=True)),
                ('event_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventseries')),
            ],
            options={
                'ordering': ('-start_datetime', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('host', 'Host'), ('instructor', 'Instructor'), ('speaker', 'Speaker')], default='host', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host_links', to='events.event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_host_links', to='events.host')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventHost', to='events.host'),
        ),
        migrations.CreateModel(
            name='EventAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('legacy_date_path', 'Legacy date/title path'), ('legacy_uuid', 'Legacy UUID path'), ('legacy_path', 'Legacy path'), ('title_slug', 'Previous title slug'), ('reviewed', 'Reviewed alias')], max_length=24)),
                ('reason', models.CharField(max_length=255)),
                ('source_repository', models.CharField(blank=True, default='', max_length=255)),
                ('source_revision', models.CharField(blank=True, default='', max_length=64)),
                ('source_key', models.CharField(blank=True, default='', max_length=512)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='events.event')),
            ],
            options={
                'ordering': ('source_path',),
                'constraints': [models.CheckConstraint(condition=models.Q(('source_path__startswith', '/events/'), models.Q(('source_path__contains', '?'), _negated=True), models.Q(('source_path__contains', '#'), _negated=True)), name='events_alias_path_shape')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventhost',
            constraint=models.UniqueConstraint(fields=('event', 'host', 'role'), name='events_event_host_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventhost',
            constraint=models.UniqueConstraint(fields=('event', 'position'), name='events_event_host_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__isnull', True), ('end_datetime__gte', models.F('start_datetime')), _connector='OR'), name='events_event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('public_id__isnull', True), ('public_id__gt', 0), _connector='OR'), name='events_event_public_id_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('event_series__isnull', False), ('series_position__isnull', False)), fields=('event_series', 'series_position'), name='events_event_series_position_unique'),
        ),
        migrations.RunPython(create_public_id_sequence, migrations.RunPython.noop),
    ]
