# Generated by Django 6.0.8 on 2026-09-05 19:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0004_emaildelivery_transport_options'),
        ('events', '0001_provisional_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_email', models.EmailField(max_length=254)),
                ('normalized_email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('attended', 'Attended'), ('no_show', 'No show')], db_index=True, default='pending_verification', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_notice_version', models.CharField(blank=True, default='', max_length=40)),
                ('privacy_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('newsletter_consent', models.BooleanField(blank=True, null=True)),
                ('newsletter_consent_version', models.CharField(blank=True, default='', max_length=40)),
                ('newsletter_consent_source', models.CharField(blank=True, default='', max_length=80)),
                ('newsletter_consented_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition_metadata', models.JSONField(blank=True, default=dict)),
                ('abuse_metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('would_change', models.TextField(blank=True, default='')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='events.eventregistration')),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_version', models.PositiveIntegerField()),
                ('interval', models.CharField(max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_reminders', to='cb_mail.emaildelivery')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='events.eventregistration')),
            ],
            options={
                'ordering': ('scheduled_for', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SeriesOccurrenceOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_opt_outs', to='events.event')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_opt_outs', to='events.eventseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_series_occurrence_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SeriesRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_registrations', to='events.eventseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_series_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'normalized_email'), name='events_registration_event_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='events_registration_event_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='events_registration_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventreminder',
            constraint=models.UniqueConstraint(fields=('registration', 'registration_version', 'interval'), name='events_reminder_registration_version_interval_unique'),
        ),
        migrations.AddConstraint(
            model_name='seriesoccurrenceoptout',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='events_series_occurrence_opt_out_unique'),
        ),
        migrations.AddConstraint(
            model_name='seriesregistration',
            constraint=models.UniqueConstraint(fields=('series', 'user'), name='events_series_registration_unique'),
        ),
    ]
