# Generated by Django 6.0.8 on 2026-09-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_provisional_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIntegrationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('provider_requested', 'Provider requested'), ('succeeded', 'Succeeded'), ('ambiguous', 'Ambiguous'), ('rejected', 'Rejected')], default='starting', max_length=24)),
                ('result_reference', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_attempts', to='events.event')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
