# Generated by Django 6.0.8 on 2026-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_provisional_integration_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public listing'), ('hidden', 'Hidden series')], default='public', help_text="Issue #249: 'hidden' removes every occurrence of this series from discovery surfaces (public listings, sitemaps, feeds) for every viewer. This is separate from 'is_active', which only affects the series' own public page. The series and its events stay reachable by direct URL and keep working for recaps and registration.", max_length=10),
        ),
    ]
