# Generated by Django 6.0.8 on 2026-09-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cb_content_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_content_sync.contentsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_key'), name='test_fixture_content_source_key')],
            },
        ),
    ]
