# Generated by Django 6.0.8 on 2026-09-07 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_provisional_integration_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('auto_banner_url', models.URLField(blank=True, default='', max_length=500)),
                ('custom_banner_url', models.URLField(blank=True, default='', max_length=500)),
                ('required_level', models.IntegerField(choices=[(0, 'Open (everyone)'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], default=0)),
                ('default_unit_required_level', models.IntegerField(blank=True, choices=[(0, 'Open (everyone)'), (5, 'Registered users'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], help_text='Default access level applied to every unit in this course unless the unit overrides it. When null, units inherit Course.required_level.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('discussion_url', models.URLField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('github_repo_url', models.URLField(blank=True, default='', max_length=500)),
                ('docs_url', models.URLField(blank=True, default='', max_length=500)),
                ('faq_url', models.URLField(blank=True, default='', max_length=500)),
                ('hashtag', models.CharField(blank=True, default='', max_length=100)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('slug', models.SlugField(default='', max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('mode', models.CharField(choices=[('cohort', 'Cohort'), ('self_paced', 'Self-paced')], default='cohort', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, default='', max_length=500)),
                ('curriculum_format', models.CharField(choices=[('legacy', 'Legacy'), ('modules', 'Modules')], default='legacy', max_length=20)),
                ('hashtag', models.CharField(blank=True, default='', max_length=100)),
                ('finished', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('project_passing_score', models.IntegerField(default=0)),
                ('min_projects_to_pass', models.IntegerField(default=1)),
                ('first_homework_scored', models.BooleanField(default=False)),
                ('homework_problems_comments_field', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='cb_curriculum.course')),
            ],
            options={
                'ordering': ('start_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order; 0 is the primary instructor.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_curriculum.course')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_instructor_links', to='events.host')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses', through='cb_curriculum.CourseInstructor', to='events.host'),
        ),
        migrations.CreateModel(
            name='CurriculumImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_uuid', models.UUIDField()),
                ('source_stable_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9._-]{0,127}$', 'Enter a canonical source stable ID.')])),
                ('repository_owner', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$', 'Enter a canonical repository owner or name.')])),
                ('repository_name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$', 'Enter a canonical repository owner or name.')])),
                ('repository_branch', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$', 'Enter a canonical repository branch.')])),
                ('commit_sha', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('schema_version', models.PositiveIntegerField()),
                ('parser_version', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$', 'Enter a canonical source version.')])),
                ('state', models.CharField(choices=[('received', 'Received'), ('validating', 'Validating'), ('applying', 'Applying'), ('succeeded', 'Succeeded'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='received', max_length=16)),
                ('manifest_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['source_uuid', 'state', '-created_at'], name='cb_curr_import_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_uuid', 'commit_sha', 'parser_version'), name='cb_curriculum_import_identity_uq'), models.CheckConstraint(condition=models.Q(('commit_sha__regex', '[0-9a-f]{40}')), name='cb_curriculum_import_commit_ck'), models.CheckConstraint(condition=models.Q(('manifest_checksum__isnull', True), ('manifest_checksum__regex', '[0-9a-f]{64}'), _connector='OR'), name='cb_curriculum_import_manifest_ck'), models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='cb_curriculum_import_schema_ck')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('unenrolled_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto_progress', 'Auto (first lesson complete)'), ('admin', 'Admin (Studio)')], default='manual', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('display_on_leaderboard', models.BooleanField(default=True)),
                ('display_public_profile', models.BooleanField(default=False)),
                ('position_on_leaderboard', models.IntegerField(blank=True, null=True)),
                ('disable_learning_in_public', models.BooleanField(default=False)),
                ('certificate_name', models.CharField(blank=True, default='', max_length=255)),
                ('total_score', models.IntegerField(default=0)),
                ('certificate_url', models.CharField(blank=True, default='', max_length=500)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cb_curriculum.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-enrolled_at',),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='cb_curriculum.enrollment')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('slug', models.SlugField(default='', max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('overview', models.TextField(blank=True, default='')),
                ('overview_html', models.TextField(blank=True, default='', editable=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cb_curriculum.cohort')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('slug', models.SlugField(default='', max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='', editable=False)),
                ('homework', models.TextField(blank=True, default='')),
                ('homework_html', models.TextField(blank=True, default='', editable=False)),
                ('timestamps', models.JSONField(blank=True, default=list)),
                ('is_preview', models.BooleanField(default=False)),
                ('required_level', models.IntegerField(blank=True, choices=[(0, 'Open (everyone)'), (5, 'Registered users'), (10, 'Basic and above'), (20, 'Main and above'), (30, 'Premium only')], null=True)),
                ('available_after_days', models.IntegerField(blank=True, help_text='Cohort drip schedule: the unit becomes available this many days after the cohort start date. Null means available immediately.', null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=32)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='cb_curriculum.module')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='UnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='cb_curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='cb_cohort_course_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'self_paced')), fields=('course',), name='cb_cohort_self_paced_unique'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_cohort_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course', 'host'), name='cb_course_host_unique'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('unenrolled_at__isnull', True)), fields=('user', 'cohort'), name='cb_enrollment_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('cohort', 'slug'), name='cb_module_cohort_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_module_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='cb_unit_module_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_unit_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='unitprogress',
            constraint=models.UniqueConstraint(fields=('user', 'unit'), name='cb_unit_progress_user_unit_unique'),
        ),
    ]
