# Generated by Django 6.0.8 on 2026-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cb_curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("homework", "Homework"),
                    ("event", "Event"),
                    ("checklist_item", "Checklist item"),
                ],
                db_default="lesson",
                default="lesson",
                max_length=20,
            ),
        ),
    ]
