# Generated by Django 6.0.8 on 2026-09-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0001_initial'),
        ('events', '0003_provisional_integration_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_instructor_links', to='events.host'),
        ),
    ]
