# Generated by Django 6.0.8 on 2026-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cb_curriculum", "0002_alter_unit_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="body_html_source",
            field=models.CharField(
                choices=[
                    ("markdown", "Rendered from the markdown body"),
                    ("site", "Supplied by the parser"),
                ],
                default="markdown",
                help_text="Where body_html comes from: this app's markdown renderer, or the sync parser. Supplied HTML is sanitized on every save but never re-rendered.",
                max_length=20,
            ),
        ),
    ]
