# Generated by Django 6.0.8 on 2026-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cb_curriculum", "0003_unit_body_html_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="syllabus_section",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Optional syllabus heading displayed before this top-level module.",
                max_length=255,
            ),
        ),
    ]
