# Generated by Django 6.0.8 on 2026-09-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0004_module_syllabus_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='source_sibling_position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_sibling_position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
