# Generated by Django 6.0.8 on 2026-09-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_curriculum', '0004_module_syllabus_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set to make this module a child of another module.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cb_curriculum.module'),
        ),
    ]
