# Generated by Django 6.0.8 on 2026-10-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cb_curriculum", "0005_module_unit_source_sibling_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("unenrolled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto_progress", "Auto (first lesson complete)"),
                            ("admin", "Admin (Studio)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to="cb_curriculum.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-enrolled_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("unenrolled_at__isnull", True)),
                        fields=("user", "course"),
                        name="cb_course_enroll_active_uq",
                    )
                ],
            },
        ),
    ]
