# Generated by Django 6.0.8 on 2026-09-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='SettingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(db_index=True, max_length=255)),
                ('old_value', models.JSONField(null=True)),
                ('old_value_redacted', models.BooleanField(default=False)),
                ('new_value', models.JSONField(null=True)),
                ('new_value_redacted', models.BooleanField(default=False)),
                ('actor_ref', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
