# Generated by Django 6.0.8 on 2026-09-16 14:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_submission_review_state(apps, schema_editor):
    """Mirror each submission's project state onto the new per-submission field.

    C5.2f: leaderboard and statistics now read ``ProjectSubmission.review_state`` instead of
    ``Project.state``. Without this backfill, every submission of an already-``COMPLETED`` or
    ``PEER_REVIEWING`` project would default to ``AWAITING_ASSIGNMENT`` and silently drop out of
    the leaderboard's completed-projects list and out of project statistics. ``CLOSED`` and
    ``COLLECTING_SUBMISSIONS`` projects need no change: their submissions are correctly still
    ``AWAITING_ASSIGNMENT``, the field's default.
    """

    ProjectSubmission = apps.get_model("cb_coursework", "ProjectSubmission")
    state_to_review_state = {"CO": "SC", "PR": "IR"}
    for project_state, review_state in state_to_review_state.items():
        ProjectSubmission.objects.filter(project__state=project_state).update(
            review_state=review_state
        )


def noop_reverse(apps, schema_editor):
    """No reverse backfill: the field itself is dropped by the reverse AddField."""


class Migration(migrations.Migration):
    dependencies = [
        ("cb_coursework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pooled_review_window_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="review_state",
            field=models.CharField(
                choices=[("AW", "AWAITING_ASSIGNMENT"), ("IR", "IN_REVIEW"), ("SC", "SCORED")],
                default="AW",
                max_length=2,
            ),
        ),
        migrations.RunPython(backfill_submission_review_state, noop_reverse),
        migrations.AlterField(
            model_name="peerreview",
            name="state",
            field=models.CharField(
                choices=[("TR", "TO_REVIEW"), ("SU", "SUBMITTED"), ("EX", "EXPIRED")],
                default="TR",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="PeerReviewBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("formed_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_batches",
                        to="cb_coursework.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="peerreview",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="cb_coursework.peerreviewbatch",
            ),
        ),
    ]
