# Generated by Django 6.0.8 on 2026-09-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_coursework', '0002_project_pooled_review_window_days_and_more'),
        ('cb_curriculum', '0003_unit_body_html_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='cb_curriculum.module'),
        ),
        migrations.AddField(
            model_name='homework',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='cb_curriculum.unit'),
        ),
    ]
