# Generated by Django 6.0.8 on 2026-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_coursework', '0003_homework_module_homework_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='peer_review_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
