# Generated by Django 6.0.8 on 2026-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_coursework', '0003_homework_module_homework_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='final_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='step_label',
            field=models.TextField(blank=True, default=''),
        ),
    ]
