# Generated by Django 6.0.8 on 2026-10-02 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_coursework', '0006_project_module_commit_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='github_link',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
