# Generated by Django 6.0.8 on 2026-09-21 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_key', models.CharField(max_length=255)),
                ('answers', models.JSONField(default=dict)),
                ('final_fields', models.JSONField(default=dict)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'assignment_key'), name='cb_homework_draft_identity_uq')],
            },
        ),
    ]
