# Generated by Django 6.0.8 on 2026-09-05 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cb_jobs', '0002_jobintent_cb_jobs_external_id_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('purpose', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('template_key', models.CharField(max_length=128)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('context_hash', models.CharField(max_length=64)),
                ('sender_id', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('leased', 'Leased'), ('provider_accepted', 'Provider accepted'), ('delivered', 'Delivered'), ('retryable', 'Retryable'), ('ambiguous', 'Ambiguous'), ('suppressed', 'Suppressed'), ('dead', 'Dead'), ('hard_bounced', 'Hard bounced'), ('complained', 'Complained')], default='pending', max_length=32)),
                ('external_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('reason_code', models.CharField(blank=True, default='', max_length=128)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=128)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='cb_jobs.jobintent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_base_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('leased', 'Leased'), ('provider_accepted', 'Provider accepted'), ('delivered', 'Delivered'), ('retryable', 'Retryable'), ('ambiguous', 'Ambiguous'), ('suppressed', 'Suppressed'), ('dead', 'Dead'), ('hard_bounced', 'Hard bounced'), ('complained', 'Complained')], max_length=32)),
                ('reason_code', models.CharField(blank=True, default='', max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='cb_mail.emaildelivery')),
            ],
            options={
                'ordering': ('received_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PendingUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unsubscribe_token', models.CharField(max_length=128, unique=True)),
                ('token_fingerprint', models.CharField(db_index=True, max_length=32)),
                ('scope', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, default='', max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'accepted_at'], name='cb_mail_unsub_status')],
            },
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['state', 'created_at'], name='cb_mail_state_created'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['purpose', 'created_at'], name='cb_mail_purpose_created'),
        ),
    ]
