# Generated by Django 6.0.8 on 2026-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='context_data',
            field=models.JSONField(default=dict),
        ),
    ]
