# Generated by Django 6.0.8 on 2026-09-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0002_emaildelivery_context_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackevent',
            name='event_type',
            field=models.CharField(default='delivery.updated', max_length=64),
        ),
        migrations.AlterField(
            model_name='callbackevent',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='cb_mail.emaildelivery'),
        ),
        migrations.AlterField(
            model_name='callbackevent',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('queued', 'Queued'), ('leased', 'Leased'), ('provider_accepted', 'Provider accepted'), ('delivered', 'Delivered'), ('retryable', 'Retryable'), ('ambiguous', 'Ambiguous'), ('suppressed', 'Suppressed'), ('dead', 'Dead'), ('hard_bounced', 'Hard bounced'), ('complained', 'Complained')], default='', max_length=32),
        ),
    ]
