# Generated by Django 6.0.8 on 2026-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cb_mail", "0003_callbackevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="transport_options",
            field=models.JSONField(default=dict),
        ),
    ]
