# Generated by Django 6.0.8 on 2026-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_mail', '0004_emaildelivery_transport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackevent',
            name='sequence',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callbackevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='cb_mail_cb_type_time'),
        ),
    ]
