# Generated by Django 6.0.8 on 2026-09-16 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBasePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('wiki', 'Wiki'), ('docs', 'Documentation')], default='docs', max_length=20)),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='', editable=False)),
                ('nav_order', models.IntegerField(default=0, help_text='Position among siblings; ties break by title, then slug.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('parent', models.ForeignKey(blank=True, help_text='Documentation tree parent. Wiki pages must leave this null.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cb_knowledge_base.knowledgebasepage')),
            ],
            options={
                'ordering': ('section', 'slug'),
                'indexes': [models.Index(fields=['section', 'status'], name='cb_kb_section_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'slug'), name='cb_kb_page_section_slug_unique'), models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_kb_page_source_complete')],
            },
        ),
    ]
