# Generated by Django 6.0.8 on 2026-09-17 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgebasepage',
            name='cb_kb_page_section_slug_unique',
        ),
        migrations.AlterField(
            model_name='knowledgebasepage',
            name='slug',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_.]+(?:/[-a-zA-Z0-9_.]+)*$', 'Enter a slug: letters, digits, dots, dashes or underscores, optionally in several segments joined by a slash.')]),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasepage',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('section', 'parent', 'slug'), name='cb_kb_page_child_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasepage',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('section', 'slug'), name='cb_kb_page_root_slug_unique'),
        ),
    ]
