# Generated by Django 6.0.8 on 2026-09-17 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_knowledge_base', '0002_page_key_scoped_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasepage',
            name='public_path',
            field=models.CharField(blank=True, default=None, help_text='Site-owned public URL path. Null derives the path from the ancestor chain, which is what a site that does not own its routes wants.', max_length=500, null=True, validators=[django.core.validators.RegexValidator('^/[^\\s?#]*$', 'Enter a root-relative path starting with a slash, without whitespace, query or fragment.')]),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasepage',
            constraint=models.UniqueConstraint(condition=models.Q(('public_path__isnull', False)), fields=('public_path',), name='cb_kb_page_public_path_unique'),
        ),
    ]
