# Generated by Django 6.0.8 on 2026-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_knowledge_base', '0003_page_public_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasepage',
            name='body_html_source',
            field=models.CharField(choices=[('markdown', 'Rendered from the markdown body'), ('site', 'Supplied by the site')], default='markdown', help_text="Where body_html comes from: this app's markdown renderer, or the site. Site-supplied HTML is sanitized on every save but never re-rendered.", max_length=20),
        ),
    ]
