# Generated by Django 6.0.8 on 2026-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_knowledge_base', '0004_page_body_html_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasepage',
            name='record',
            field=models.JSONField(blank=True, default=dict, help_text='Section-shaped metadata owned by the site. The package stores and returns it and never reads a key of it; put site-specific fields here, not in new columns.'),
        ),
    ]
