"""Separate the two meanings that shared ``source_content_id`` (issue C7.9c).

The content format reserves ``source_content_id`` for the item's own
``content_id`` (``content_sync/FORMAT.md`` section 3.4). ``knowledge_base.sync``
stored the ``ContentSource`` primary key there instead and scoped
``delete_missing`` by it. Both are ``UUIDField``, so the two meanings collided
silently rather than raising.

What this migration does with the values already stored, and why:

- a value that names a ``ContentSource`` row is a source primary key, so it
  moves into the new ``source`` foreign key and the column is cleared. Nothing
  is lost: the same identifier now sits in the field that means it, and
  ``delete_missing`` reads it there;
- a value that names no ``ContentSource`` row is a pointer to a source that was
  deleted. It can be neither moved (there is no row to point at) nor read as an
  item ``content_id`` (it never was one), so it is dropped deliberately. Such a
  row is already outside every sync's ownership scope and keeps its path,
  commit and checksum;
- no row is created, deleted or re-parented. The only column written is
  ``source_content_id``, and the only column filled is ``source_id``.

Reversing restores ``source_content_id`` from ``source_id`` for every row the
first bullet moved, which is what the old code would find there, and then drops
the column. The second bullet is not restored: the dropped value pointed at
nothing.

``source_content_id`` also leaves the all-or-nothing provenance set, because a
parser whose shape carries no ``content_id`` (every site parser written before
the format) fills the other three and not this one.
"""

# Generated by Django 6.0.8 on 2026-09-17 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def move_source_ids(apps, schema_editor):
    """Move the stored source primary keys into the source foreign key."""

    page_model = apps.get_model("cb_knowledge_base", "KnowledgeBasePage")
    source_model = apps.get_model("cb_content_sync", "ContentSource")
    known = list(source_model.objects.values_list("pk", flat=True))
    page_model.objects.filter(source_content_id__in=known).update(
        source_id=F("source_content_id"), source_content_id=None
    )
    page_model.objects.exclude(source_content_id=None).update(source_content_id=None)


def restore_source_ids(apps, schema_editor):
    """Put the source primary key back where the old code looked for it."""

    page_model = apps.get_model("cb_knowledge_base", "KnowledgeBasePage")
    page_model.objects.exclude(source=None).update(source_content_id=F("source_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('cb_content_sync', '0001_initial'),
        ('cb_knowledge_base', '0005_page_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgebasepage',
            name='cb_kb_page_source_complete',
        ),
        migrations.AddField(
            model_name='knowledgebasepage',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The content source this row was synced from. Null for Studio-authored rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_base_pages', to='cb_content_sync.contentsource'),
        ),
        migrations.AlterField(
            model_name='knowledgebasepage',
            name='record',
            field=models.JSONField(blank=True, default=dict, help_text='Section-shaped metadata. The package stores and returns it and never reads a key of it; put parser-owned and site-specific fields here, not in new columns.'),
        ),
        migrations.RunPython(move_source_ids, restore_source_ids),
        migrations.AddConstraint(
            model_name='knowledgebasepage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_kb_page_source_complete'),
        ),
    ]
