"""The person record the `person` kind fills (issue C7.9c, decisions D24, D31).

A new table and nothing else: no existing row is read or written. The kind is
an optional instructor source, so a site decides whether to fill it.
"""

# Generated by Django 6.0.8 on 2026-09-17.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_content_sync', '0001_initial'),
        ('cb_knowledge_base', '0006_page_source_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('body', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='', editable=False)),
                ('body_html_source', models.CharField(choices=[('markdown', 'Rendered from the markdown body'), ('site', 'Supplied by the site')], default='markdown', help_text="Where body_html comes from: this app's markdown renderer, or the site. Site-supplied HTML is sanitized on every save but never re-rendered.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_.]+(?:/[-a-zA-Z0-9_.]+)*$', 'Enter a slug: letters, digits, dots, dashes or underscores, optionally in several segments joined by a slash.')])),
                ('title', models.CharField(help_text='The display name.', max_length=300)),
                ('summary', models.TextField(blank=True, default='', help_text='The short bio.')),
                ('image', models.CharField(blank=True, default='', help_text='The picture, as the media store returned it.', max_length=500)),
                ('links', models.JSONField(blank=True, default=list, help_text="A list of {label, url}; the label is one of the kind's declared labels.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('record', models.JSONField(blank=True, default=dict, help_text='Metadata shaped by whoever writes the row. The package stores and returns it and never reads a key of it.')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ('title', 'slug'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The content source this row was synced from. Null for Studio-authored rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='cb_content_sync.contentsource'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'slug'], name='cb_kb_person_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '[0-9a-f]{40}'), ('source_checksum__regex', '[0-9a-f]{64}')), _connector='OR'), name='cb_kb_person_source_complete'),
        ),
    ]
