# Generated by Django 6.0.8 on 2026-09-05 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('repo_name', models.CharField(max_length=300, unique=True)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('skipped', 'Skipped')], default='', max_length=20)),
                ('last_sync_log', models.TextField(blank=True, default='')),
                ('sync_locked_at', models.DateTimeField(blank=True, null=True)),
                ('sync_requested', models.BooleanField(default=False)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_commit', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('max_files', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('repo_name',),
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('event_type', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('deduplication_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['service', 'processed', 'received_at'], name='cb_sync_service_state_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_unchanged', models.IntegerField(default=0)),
                ('items_deleted', models.IntegerField(default=0)),
                ('items_detail', models.JSONField(blank=True, default=list)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='cb_content_sync.contentsource')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['source', 'status', '-started_at'], name='cb_sync_src_status_idx'), models.Index(fields=['batch_id', '-started_at'], name='cb_sync_batch_started_idx')],
            },
        ),
    ]
