# Generated by Django 6.0.8 on 2026-09-05 10:45

import community_base.api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.CharField(default=community_base.api.models.generate_key_identifier, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key_hash', models.CharField(max_length=128)),
                ('lookup_prefix', models.CharField(db_index=True, max_length=32)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('kind', models.CharField(choices=[('staff', 'Staff'), ('member', 'Member')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_base_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['lookup_prefix', 'revoked_at'], name='cb_api_key_lookup'), models.Index(fields=['user', 'revoked_at'], name='cb_api_key_owner')],
            },
        ),
    ]
