# Generated by Django 6.0.8 on 2026-09-05 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handler', models.CharField(max_length=128)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('available_at', models.DateTimeField()),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('last_error', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('available_at', 'created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'available_at'], name='cb_jobs_due'), models.Index(fields=['status', 'lease_expires_at'], name='cb_jobs_lease'), models.Index(fields=['correlation_id'], name='cb_jobs_correlation')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='cb_jobs_max_attempts_positive'), models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='cb_jobs_attempts_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('status', 'running')), models.Q(models.Q(('status', 'running'), _negated=True), ('lease_token__isnull', True), ('lease_expires_at__isnull', True)), _connector='OR'), name='cb_jobs_lease_state_consistent')],
            },
        ),
    ]
