# Generated by Django 6.0.8 on 2026-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobintent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='cb_jobs_external_id_unique'),
        ),
    ]
